CREATE TABLE `leads` (
	`id` int AUTO_INCREMENT NOT NULL,
	`leadType` varchar(64) NOT NULL,
	`name` varchar(255),
	`phone` varchar(32) NOT NULL,
	`email` varchar(320),
	`city` varchar(128),
	`notes` text,
	`vehicleYear` varchar(8),
	`vehicleMake` varchar(64),
	`vehicleModel` varchar(64),
	`vehicleCondition` varchar(32),
	`titleStatus` varchar(32),
	`businessName` varchar(255),
	`contactName` varchar(255),
	`businessType` varchar(64),
	`vehicleCount` varchar(32),
	`vehicleTypes` text,
	`pickupTiming` varchar(64),
	`vehicleAccessibility` text,
	`needPickupToday` varchar(8),
	`source` varchar(128),
	`status` varchar(32) NOT NULL DEFAULT 'new',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `leads_id` PRIMARY KEY(`id`)
);
